"""The generated CLI as an operator actually runs it: a real process, real hardware.

Everything in ``tests/test_cli_generated.py``, ``test_cli_main.py`` and
``test_cli_tiers.py`` calls ``main(argv)`` in-process with fakes underneath. That
is the right place for the tier table, the argument coercion and the lifecycle
overrides, and it proves all of them. What it cannot prove is the two claims that
are properties of *a process against a device*:

1. **A subcommand generated by reflection actually drives the instrument**, end
   to end, through the real open/call/teardown lifecycle in a process that exits
   inside a second. An in-process test shares the interpreter with pytest, so it
   never exercises the thing the CLI exists to do: start cold, open, read, tear
   down, exit. If the implicit open were wrong, or teardown deadlocked, only a
   real invocation would show it.

2. **The exit codes are what a shell script sees.** ``main()`` returning 3 and
   ``$? == 3`` are different claims — the second also depends on ``__main__``,
   on nothing swallowing the return value, and on no traceback escaping. Scripts
   branch on ``$?``, so ``$?`` is what gets asserted here.

Why the gate tests live here rather than only in-process
--------------------------------------------------------

The refusal path is the one case where hardware is *irrelevant by construction*:
the gate is checked before the device is opened (``cli_generated._check_tier``),
so a refusal is a refusal with nothing attached. That makes an in-process test
sufficient for the message, and it exists. What is asserted here instead is the
part that needs the device: that a satisfied gate does **not** stop at the gate
but goes on to reach the instrument. A test that only shows "no ``--yes`` → 3"
cannot tell a working gate from one that refuses everything; the pair can.

So the discriminator is the exit code of the *satisfied* case, and it is checked
against a real device rather than against an absent one. With no ADU218 present
the satisfied run also fails — with 2, the connection code — and 2-vs-3 would
then be indistinguishable from a gate that never opened anything.

What this file deliberately does not do
---------------------------------------

**It does not switch a relay it was not told it may switch.** ``adu218
set-relay-state`` needs ``--yes``, and the CLI has no ``allowed_relays`` flag on
purpose (an allowlist a caller can widen per invocation is not an allowlist), so
a CLI write reaches whatever relay is named with the driver's permissive default.
The write test therefore takes the same ``BENCHCTRL_ADU218_RELAY`` nomination as
``test_hardware_ontrak_adu218.py`` and skips without an explicit opt-in, and it
restores the relay afterwards through the CLI's own de-energising path — which
is also how ``reset-relays`` gets exercised as the tier-2 case it is classified
as.

**It does not arm the watchdog.** ``set-watchdog`` is the one env-gated ADU218
tool, and its consequence outlives the process: the relays drop by timeout after
the CLI has exited, with nothing left to feed it. The trip itself is witnessed on
hardware in ``test_hardware_ontrak_adu218.py`` with the DMM across the contact
and an explicit opt-in. Here only the *refusal* is checked, which needs no arming.

Running it
----------

The ADU218 is found by USB descriptor; there is no address to supply. Every test
skips if it is not attached, because "not plugged in" is a fact about the bench
and a red test for it trains people to ignore this file.

    BENCHCTRL_ADU218_RELAY       the relay a CLI write may switch (default 7)
    BENCHCTRL_CLI_HW_WRITE=1     allow the one CLI relay write (default: skip)

These run on the **bench machine**, against local devices — the board carries
the hardware, so ``python3 -m benchctrl adu218 …`` there needs no endpoint
token. Nothing here uses ``--remote``: that path is covered by
``tests/test_remote_ontrak_adu218.py``, and pointing it at a board whose agent
holds the writer claim would test claim contention rather than the CLI.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest

pytestmark = pytest.mark.hardware

#: The relay a CLI write may switch. Same variable and same default as
#: ``test_hardware_ontrak_adu218.TEST_RELAY``, deliberately: two files
#: disagreeing about which relay is safe to move is exactly the drift that ends
#: with a leads-connected contact switching under a DMM that is mid-reading.
TEST_RELAY = int(os.environ.get("BENCHCTRL_ADU218_RELAY", "7"))

#: Timeout for one invocation. A CLI one-shot opens, calls and exits well inside
#: a second on this hardware; this is generous so a slow USB enumeration is not
#: reported as a hang, while still failing rather than blocking the suite.
RUN_TIMEOUT_S = 60.0


def _run(*args: str, env_extra: dict | None = None) -> subprocess.CompletedProcess:
    """One real ``benchctrl`` process, captured.

    Invoked as ``-m benchctrl`` rather than the console script because the board
    has no pip and reaches the package through ``PYTHONPATH`` — the console
    script is not installed there, and a test that needs it would skip on the
    one machine that has the instruments.

    ``sys.executable`` rather than ``python3`` so the subprocess is the same
    interpreter running the tests, and a passing test cannot be a different
    Python finding a different copy of the package.
    """
    env = dict(os.environ)
    if env_extra:
        env.update(env_extra)
    return subprocess.run(
        [sys.executable, "-m", "benchctrl", *args],
        capture_output=True,
        text=True,
        timeout=RUN_TIMEOUT_S,
        env=env,
    )


def _skip_unless_adu_present() -> None:
    """Skip the module's device tests unless a real ADU218 answers.

    Probes with a *read* subcommand, which is the CLI path under test — so a
    skip here means the CLI cannot reach the device, which is the same condition
    the tests care about. Keying the skip on the driver directly would let a
    broken CLI skip instead of fail.
    """
    proc = _run("adu218", "info")
    if proc.returncode != 0:
        pytest.skip(
            f"ADU218 not reachable through the CLI (rc={proc.returncode}): "
            f"{proc.stderr.strip()[:200]}"
        )


@pytest.fixture(scope="module")
def adu_present() -> None:
    _skip_unless_adu_present()


@pytest.fixture()
def cli_writable(adu_present) -> int:
    """The relay a CLI write may switch, or a skip, with the relay restored.

    De-energises through ``reset-relays`` on the way out rather than
    ``set-relay-state <n> off``: it is the driver's allowlist-bypassing safe
    path, so the restore cannot itself be refused, and it recovers the bench
    even if the test died between the two writes.
    """
    if os.environ.get("BENCHCTRL_CLI_HW_WRITE") != "1":
        pytest.skip(
            "set BENCHCTRL_CLI_HW_WRITE=1 to let the CLI switch relay "
            f"{TEST_RELAY}. The CLI has no allowed_relays flag, so a write "
            "reaches whatever relay is named"
        )
    try:
        yield TEST_RELAY
    finally:
        _run("--yes", "adu218", "reset-relays")


# ---------------------------------------------------------------------------
# A generated subcommand reaches the instrument
# ---------------------------------------------------------------------------


def test_a_generated_read_reaches_the_real_device(adu_present):
    """The whole point of the feature, as one process.

    ``relay-states`` is the question that motivated the CLI, and it is generated
    — nothing about this subcommand was hand-written, so a pass shows reflection
    over ``_TOOLS`` produced something that works against silicon rather than
    something that merely parses.

    Asserts on the *identity* fields rather than the relay states, because the
    states are whatever the bench is doing; the model and the relay count are
    facts about the device, so a wrong device or a stubbed answer fails.
    """
    proc = _run("adu218", "info")

    assert proc.returncode == 0, proc.stderr
    assert "model: ADU218" in proc.stdout
    assert "relay_count: 8" in proc.stdout


def test_json_output_is_parseable_and_carries_the_device_shape(adu_present):
    """``--json`` is the machine contract, so it must parse and be complete.

    The default rendering is lossy on purpose (``on``/``off`` for booleans), so
    a script that needs the value reads ``--json``. Asserting it parses *and*
    carries all eight relays as bools is what makes it usable: a renderer that
    leaked its formatting into the JSON would still parse.
    """
    proc = _run("--json", "adu218", "relay-states")

    assert proc.returncode == 0, proc.stderr
    payload = json.loads(proc.stdout)

    assert sorted(int(k) for k in payload["relays"]) == list(range(8))
    assert all(isinstance(v, bool) for v in payload["relays"].values())

    # The mask has to agree with the per-relay dict, or a script reading one and
    # a human reading the other would draw different conclusions from the same
    # invocation. Recomputed rather than compared to a constant, since whatever
    # the bench is doing is legitimate.
    assert payload["mask"] == sum(
        1 << int(k) for k, on in payload["relays"].items() if on
    )
    assert sorted(payload["energised"]) == sorted(
        int(k) for k, on in payload["relays"].items() if on
    )


def test_booleans_render_as_on_off_against_a_real_device(adu_present):
    """The render fix, on the device whose whole answer is on/off.

    ``adu218_relay_states`` returns a *nested* dict, which is where a
    JSON-dumping renderer produced ``relays: {"0": false, …}`` — the bool
    rendering never reaching the values that needed it most. Checked here rather
    than only in-process because the fixture that exposed it is the real tool's
    real return shape, and a hand-built fixture is what let it through.
    """
    proc = _run("adu218", "relay-states")

    assert proc.returncode == 0, proc.stderr
    assert "0=off" in proc.stdout or "0=on" in proc.stdout
    assert "false" not in proc.stdout.lower()
    assert "True" not in proc.stdout


def test_a_nested_collection_is_bracketed_not_dumped(adu_present):
    """``input-states`` returns dict-of-lists — the other shape the fix covers.

    The separators would otherwise merge: ``ports: A=off, off, off, B=…`` cannot
    be read. This is the case that justifies bracketing one level down while
    leaving the top level bare.
    """
    proc = _run("adu218", "input-states")

    assert proc.returncode == 0, proc.stderr
    assert "ports: A=[" in proc.stdout
    assert "B=[" in proc.stdout
    assert "{" not in proc.stdout


# ---------------------------------------------------------------------------
# The exit-code contract, as a shell sees it
# ---------------------------------------------------------------------------


def test_a_refused_write_exits_3_and_sends_nothing():
    """No ``--yes`` on a tier-1 tool: 3, and the operator is told nothing moved.

    Runs with no device fixture on purpose — the gate is checked before the open,
    so this must hold whether or not an ADU218 is attached, and a version that
    needed the device would be asserting the wrong thing.

    3 rather than 2 is the load-bearing half: a script has to be able to tell
    "you did not authorise this" from "the device is not there", and both are
    non-zero.
    """
    proc = _run("adu218", "set-relay-state", str(TEST_RELAY), "on")

    assert proc.returncode == 3, (proc.returncode, proc.stderr)
    assert "needs --yes" in proc.stderr
    assert "Nothing has been sent to the device." in proc.stderr
    assert proc.stdout == ""


def test_an_env_gated_write_exits_3_with_yes_alone():
    """``--yes`` is not enough for ``set-watchdog``, and the message says why.

    Two factors because they are different claims: ``--yes`` says the command was
    intended, the variable says the operator knows what is physically attached.
    Asserting the variable is *named* matters — an operator who cannot discover
    which variable to set will reach for the source, and the gate stops being a
    gate the first time someone exports everything.
    """
    proc = _run("--yes", "adu218", "set-watchdog", "3")

    assert proc.returncode == 3, (proc.returncode, proc.stderr)
    assert "BENCHCTRL_ADU218_ARM_WATCHDOG" in proc.stderr
    assert "Nothing has been sent to the device." in proc.stderr
    assert proc.stdout == ""


def test_satisfying_the_env_gate_gets_past_it_to_the_device(adu_present):
    """The discriminator: a satisfied gate reaches the instrument.

    Without this, ``test_an_env_gated_write_exits_3_with_yes_alone`` is equally
    consistent with a gate that refuses *everything* — a permanently-closed gate
    passes every refusal assertion in this file.

    ``set-watchdog 0`` is the disarming direction, so the gate is satisfied and
    exercised while nothing is left armed after the process exits. That it
    returns 0 against a real device is the proof the gate was the only obstacle;
    with no ADU218 attached this would be 2, which is why it takes the fixture.
    """
    proc = _run(
        "--yes",
        "adu218",
        "set-watchdog",
        "0",
        env_extra={"BENCHCTRL_ADU218_ARM_WATCHDOG": "1"},
    )

    assert proc.returncode == 0, (proc.returncode, proc.stderr)
    assert "Nothing has been sent to the device." not in proc.stderr
    assert "setting: 0" in proc.stdout


def test_an_absent_device_exits_2_not_3():
    """A device the bench does not have is 2, distinct from a refusal.

    Uses a device key with no hardware on this bench, through a *read* so no
    gate is involved at all. The pairing with the refusals above is what gives
    the exit-code table meaning: 2 and 3 have to be reachable independently, or
    a script cannot branch on them.

    Deliberately takes no device fixture — both halves of that pairing are
    hardware-free, so the distinction is provable on a laptop as well as on the
    bench. Skips if the DP2031 turns out to be attached, since then 0 is the
    correct answer and the test has nothing to say.
    """
    proc = _run("dp2031", "info")
    if proc.returncode == 0:
        pytest.skip("a DP2031 is attached, so this has no absent device to use")

    assert proc.returncode == 2, (proc.returncode, proc.stderr)
    assert "benchctrl error:" in proc.stderr


# ---------------------------------------------------------------------------
# A write, once nominated
# ---------------------------------------------------------------------------


def test_a_gated_write_switches_a_real_relay_and_reads_back(cli_writable):
    """``--yes`` plus a nominated relay: the contact moves, and a second process sees it.

    The read-back is a *separate invocation*, which is the part an in-process
    test cannot do: it proves the switch outlived the process that made it. A
    one-shot CLI whose effects vanished at exit would pass every single-process
    assertion.

    Also the one place the ``disarm_watchdog=False`` lifecycle override is
    load-bearing on hardware: without it the read-back invocation's own open
    would send ``WD0``, and a read would be silently changing device state.
    """
    relay = cli_writable

    on = _run("--yes", "adu218", "set-relay-state", str(relay), "on")
    assert on.returncode == 0, on.stderr
    assert "verified: on" in on.stdout

    seen = _run("--json", "adu218", "relay-states")
    assert seen.returncode == 0, seen.stderr
    assert json.loads(seen.stdout)["relays"][str(relay)] is True

    off = _run("--yes", "adu218", "reset-relays")
    assert off.returncode == 0, off.stderr

    cleared = _run("--json", "adu218", "relay-states")
    assert cleared.returncode == 0, cleared.stderr
    assert json.loads(cleared.stdout)["relays"][str(relay)] is False


def test_reset_relays_needs_no_confirmation_on_hardware(cli_writable):
    """De-energising is tier 2, and that is checked against the device.

    The in-process test asserts the *tier table* says so. This asserts the
    device agrees: ``reset-relays`` with no ``--yes`` reaches the hardware and
    returns 0. Reaching the safe state must never need more ceremony than
    leaving it, or an operator fighting a live output has a gate in the way —
    and that property is worth proving where it would actually be used.
    """
    proc = _run("adu218", "reset-relays")

    assert proc.returncode == 0, proc.stderr
    assert "Nothing has been sent to the device." not in proc.stderr
