"""Command-line tool — ``benchctrl <command>`` / ``python -m benchctrl``.

Designed for quick one-shot operations from a shell. For anything
non-trivial, prefer the Python API.

Two families of command, and the difference is deliberate:

**Legacy Arc commands** — ``discover``, ``info``, ``set-voltage``,
``set-output``, ``set-range``, ``set-current-limit``, ``set-exp-voltage``,
``set-gpo``, ``capture``, ``stream``. Hand-written, Arc-only, documented in
``docs/getting_started.md`` since v0.1. Kept working verbatim: they open the
Arc directly, so ``--sim`` and ``--remote`` do **not** apply to them. Prefer
``benchctrl arc …``.

**Device groups** — ``benchctrl <device> <tool> …``, one subcommand per MCP
tool, generated by reflection in :py:mod:`benchctrl.cli_generated`. A tool added
to a driver appears here with no edit. Risk is *not* generated: every tool is
classified explicitly in :py:mod:`benchctrl.cli_tiers`, and lifecycle — the
open/close pair a one-shot process needs and the mode-dependent teardown — lives
in :py:mod:`benchctrl.cli_lifecycle`.

Exit codes, so a script can tell the cases apart:

====  ===========================================================
0     the command ran
1     the command ran but found nothing (``discover`` with no SMU)
2     the device or the library refused (``BenchError``)
3     the CLI refused: a missing ``--yes`` or env gate (``CliError``)
4     the command ran, but teardown could not de-energise
130   interrupted
====  ===========================================================

Code 4 exists because the alternative is worse. ``dl3031a_close`` reports a
failed load-input disable as a key in its *result*, not an exception — so a CLI
that only checked for exceptions would print the measurement and exit 0 with the
load still sinking current.
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path

from benchctrl.drivers.otii_arc import OtiiArc, OtiiArcChannel
from benchctrl._version import __version__
from benchctrl.exceptions import BenchError

log = logging.getLogger("benchctrl.cli")


def _open_smu(args) -> OtiiArc:
    if args.port:
        return OtiiArc.open(args.port)
    return OtiiArc.open()


def cmd_discover(args) -> int:
    devices = OtiiArc.discover()
    if not devices:
        print("No Arc Pro found.")
        return 1
    for d in devices:
        sn = d.serial or "-"
        print(f"  {d.port:8} name={d.name!r:10} serial={sn}")
    return 0


def cmd_info(args) -> int:
    with _open_smu(args) as smu:
        info = smu.info
        if info is not None:
            print(f"Port:           {info.port}")
            print(f"Name:           {info.name}")
            if info.serial:
                print(f"Serial:         {info.serial}")
        # Drain a brief stream to populate cached values
        time.sleep(0.5)
        smu.read_raw(0.5)
        v = smu.version()
        if v:
            print(f"Version:        {v}")
        print(f"Connected:      {smu.is_connected}")
        print(f"Range:          {smu.range or '-'}")
        print(f"Voltage:        {smu.voltage if smu.voltage is not None else '-'} V")
        print(f"Current limit:  {smu.current_limit if smu.current_limit is not None else '-'} A")
        print(f"Output:         {smu.output_enabled}")
    return 0


def cmd_set_voltage(args) -> int:
    with _open_smu(args) as smu:
        smu.set_voltage(args.value)
    return 0


def cmd_set_output(args) -> int:
    enable = args.state.lower() in ("on", "true", "1", "enable")
    with _open_smu(args) as smu:
        smu.set_output(enable)
    return 0


def cmd_set_range(args) -> int:
    with _open_smu(args) as smu:
        smu.set_range(args.range)
    return 0


def cmd_set_current_limit(args) -> int:
    with _open_smu(args) as smu:
        smu.set_current_limit(args.value)
    return 0


def cmd_set_exp_voltage(args) -> int:
    with _open_smu(args) as smu:
        smu.set_exp_voltage(args.value)
    return 0


def cmd_set_gpo(args) -> int:
    enable = args.state.lower() in ("on", "true", "1", "enable")
    with _open_smu(args) as smu:
        smu.set_gpo(args.pin, enable)
    return 0


def cmd_capture(args) -> int:
    out_path = Path(args.path)
    suffix = out_path.suffix.lower()
    channels = [OtiiArcChannel.from_code(c) for c in (args.channels or ["mv", "mc"])]

    with _open_smu(args) as smu:
        smu.enable_channels(*channels)
        with smu.record(name=out_path.stem) as rec:
            time.sleep(args.seconds)
        for ch, buf in rec._buffers.items():
            print(f"  {ch.code}: {len(buf.values)} samples ({ch.label}, {ch.unit})")
        if suffix == ".csv":
            rec.save_csv(out_path, format=args.format)
        elif suffix == ".json":
            rec.save_json(out_path)
        elif suffix == ".opensmu":
            rec.save(out_path)
        else:
            print(f"  unknown extension {suffix!r}, saving as native .opensmu")
            out_path = out_path.with_suffix(".opensmu")
            rec.save(out_path)
        print(f"Saved to {out_path}")
    return 0


def cmd_stream(args) -> int:
    deadline = time.monotonic() + args.seconds
    with _open_smu(args) as smu:
        for sample in smu.stream(seconds=args.seconds):
            print(
                f"t={sample.timestamp:7.3f} s  "
                f"{sample.channel.code} = {sample.value:10.6f} {sample.channel.unit}"
            )
            if time.monotonic() > deadline:
                break
    return 0


def cmd_generated(args) -> int:
    """Run one generated device subcommand: gate, configure, open, call, close."""
    from benchctrl import cli_generated, cli_lifecycle

    fn = args._tool_fn
    # Gate before anything is configured or opened, so a refusal cannot leave a
    # half-open port behind and costs no round trip.
    cli_generated.check_gate(fn.__name__, yes=args.yes)

    _install_session_config(args)

    result, warning = cli_lifecycle.run_tool(
        args._group,
        fn,
        cli_generated.tool_kwargs(fn, args),
        bench=cli_lifecycle.bench_open_kwargs(),
    )
    print(cli_generated.render_result(result, as_json=args.json))
    if warning:
        print(f"benchctrl: {warning}", file=sys.stderr)
        return 4
    return 0


def _install_session_config(args) -> None:
    """Bind devices to local / remote / sim before the first open.

    Without this the flags parse and are silently ignored — a device asked to be
    *simulated* would drive the real instrument. ``benchctrl-mcp`` already does
    this at startup; a one-shot CLI has the same obligation and, being one-shot,
    less chance for anyone to notice it did not.
    """
    from benchctrl import config, session

    cli_cfg = None
    if args.remote or args.local or args.sim:
        cli_cfg = config.build(
            remote=args.remote,
            local_devices=args.local or (),
            sim_devices=args.sim or (),
        )
    cfg = session.configure_from_environment(cli=cli_cfg)
    for key in config.DEVICE_KEYS:
        mode = cfg.mode_for(key)
        if mode != "local":
            # Printed, not just logged: "why did that read a simulator" is the
            # question this line answers, and stderr keeps it out of a pipe.
            print(f"benchctrl: {key} -> {mode}", file=sys.stderr)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="benchctrl",
        description="benchctrl command-line tool",
        epilog=(
            "Device groups are marked [!] for commands that change what the "
            "hardware is doing (need --yes) and [!!] for those whose effect "
            "outlives the command (need --yes and a named environment gate)."
        ),
    )
    p.add_argument("--version", action="version", version=__version__)
    p.add_argument("--port", help="serial port (e.g. COM6, /dev/ttyACM0)")

    # Device binding. docs/remote.md has documented these three as CLI flags
    # since remote mode landed; until now only benchctrl-agent had them.
    p.add_argument(
        "--remote", metavar="HOST[:PORT]", help="bind every device to that agent"
    )
    p.add_argument(
        "--local", action="append", metavar="DEVICE",
        help="force this device key back to local (repeatable)",
    )
    p.add_argument(
        "--sim", action="append", metavar="DEVICE",
        help="force this device key to a simulator (repeatable)",
    )
    p.add_argument(
        "--yes", action="store_true",
        help="authorise a command that changes what the hardware is doing",
    )
    p.add_argument("--json", action="store_true", help="emit the raw result as JSON")
    p.add_argument(
        "--verbose", "-v", action="store_true", help="log at INFO to stderr"
    )

    sub = p.add_subparsers(dest="command", required=True)

    sub.add_parser("discover", help="list connected SMUs").set_defaults(
        func=cmd_discover
    )
    sub.add_parser("info", help="show device state").set_defaults(func=cmd_info)

    sv = sub.add_parser("set-voltage", help="set main voltage (V)")
    sv.add_argument("value", type=float)
    sv.set_defaults(func=cmd_set_voltage)

    so = sub.add_parser("set-output", help="set main output enable")
    so.add_argument("state", choices=["on", "off"])
    so.set_defaults(func=cmd_set_output)

    sr = sub.add_parser("set-range", help="set measurement range")
    sr.add_argument("range", choices=["low", "high"])
    sr.set_defaults(func=cmd_set_range)

    scl = sub.add_parser("set-current-limit", help="set current limit (A)")
    scl.add_argument("value", type=float)
    scl.set_defaults(func=cmd_set_current_limit)

    sxv = sub.add_parser("set-exp-voltage", help="set expansion-port voltage (V)")
    sxv.add_argument("value", type=float)
    sxv.set_defaults(func=cmd_set_exp_voltage)

    sg = sub.add_parser("set-gpo", help="set GPO pin state")
    sg.add_argument("pin", type=int, choices=[1, 2])
    sg.add_argument("state", choices=["on", "off"])
    sg.set_defaults(func=cmd_set_gpo)

    cap = sub.add_parser("capture", help="record and save samples")
    cap.add_argument("seconds", type=float, help="recording duration")
    cap.add_argument(
        "path", help="output path (extension determines format: .opensmu/.csv/.json)"
    )
    cap.add_argument(
        "--channels", "-c", nargs="*", help="channel codes (default: mv mc)"
    )
    cap.add_argument(
        "--format", default="long", choices=["long", "wide"], help="CSV format"
    )
    cap.set_defaults(func=cmd_capture)

    st = sub.add_parser("stream", help="print live samples")
    st.add_argument("seconds", type=float, help="stream duration")
    st.set_defaults(func=cmd_stream)

    # Generated device groups, added last so the legacy commands above keep
    # their place in --help and an added driver cannot displace them.
    from benchctrl import cli_generated

    cli_generated.add_device_groups(sub)

    return p


def device_error_types() -> tuple[type, ...]:
    """Every exception class that means "the instrument or the library refused".

    ``BenchError`` alone is not enough. **No driver exception subclasses it** —
    ``ADU218Error``, ``PDU41002Error``, ``QR10xError`` and the rest all descend
    straight from ``RuntimeError`` — so a CLI catching only ``BenchError`` lets
    an ordinary "device not plugged in" escape as a raw traceback with exit
    code 1, which is already the code ``discover`` returns for "found nothing".
    A script cannot tell those apart, and a traceback is not an error message.

    The class list comes from :py:mod:`benchctrl.net.errors`, which already
    maintains it so exceptions survive the RPC wire. Reusing that registry means
    a new driver's exceptions are handled here the moment they are made
    remote-safe, rather than needing a second list to be remembered separately.
    Flattening the hierarchies into one base class would be the cleaner fix and
    is not the CLI's to make.
    """
    from benchctrl.net import errors

    return tuple(
        {
            cls
            for cls in errors._registry().values()
            # Only benchctrl's own exceptions. Catching bare OSError/ValueError
            # here would swallow genuine bugs in the CLI itself as though the
            # instrument had refused something.
            if cls.__module__.startswith("benchctrl.")
        }
    ) or (BenchError,)


#: The substring that identifies claim contention inside a ``PolicyError``.
#: Matching on text is fragile and is done anyway, because the error carries no
#: structured field to key on — ``agent.claim`` raises
#: ``PolicyError(f"{device_key} is claimed by session {holder}; …")``. The
#: fragility is contained by a test that produces the error from a *real* agent
#: with two connected clients, so a reworded server message fails the test
#: rather than silently turning the explanation back off.
CLAIM_CONFLICT_MARKER = "is claimed by session"


def claim_conflict_help(exc: BaseException) -> str | None:
    """Extra explanation when a device is held by another session, else None.

    The server's own wording is aimed at a protocol client: it names an opaque
    session id and says this session "is a read-only observer", which reads as
    though the operator asked for that. From a shell it is nearly always one
    thing — another ``benchctrl`` process, or a dashboard, got there first —
    and the fix is to wait rather than to retry harder.

    Worth saying explicitly that nothing is retried: ``RemoteClient.attach``
    calls ``agent.claim`` once, at open, before the tool runs. There is no
    queue and no backoff anywhere in ``net/client.py``, so a second invocation
    fails immediately and the device is untouched.
    """
    if CLAIM_CONFLICT_MARKER not in str(exc):
        return None
    return (
        "Another session holds the writer claim on this device — most likely a "
        "second benchctrl process or a dashboard that attached first.\n"
        "Concurrent invocations fail immediately: the claim is taken at open, "
        "before the tool runs, and nothing retries or queues. Nothing has been "
        "sent to the device.\n"
        "Wait for the other process to exit, or run the command there."
    )


def main(argv: list[str] | None = None) -> int:
    from benchctrl.cli_generated import CliError

    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "verbose", False):
        logging.basicConfig(level=logging.INFO, stream=sys.stderr)
    # A generated subcommand carries the tool; the legacy ones carry a func.
    func = getattr(args, "func", None) or cmd_generated
    try:
        return func(args)
    except CliError as exc:
        # Distinct from BenchError and given a distinct exit code: "you did not
        # authorise this" is a different thing for a script to handle than "the
        # device is not there".
        print(f"benchctrl: {exc}", file=sys.stderr)
        return 3
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        return 130
    except device_error_types() as exc:
        # The class name is kept: with eight driver hierarchies, "which kind of
        # refusal" is most of the diagnosis, and `-v` is the way to the traceback.
        print(f"benchctrl error: {type(exc).__name__}: {exc}", file=sys.stderr)
        extra = claim_conflict_help(exc)
        if extra:
            print(extra, file=sys.stderr)
        log.debug("device error", exc_info=True)
        return 2


if __name__ == "__main__":
    sys.exit(main())
